# Generated by Django 5.1.4 on 2025-03-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ImageUrl',
        ),
    ]
